version: '3.8'

services:
  backend:
    build:
      context: ./connect4-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./connect4-backend:/app
      - ./connect4-backend/venv-connect4-backend:/app/venv-connect4-backend

  frontend:
    build:
      context: ./connect4-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
